project:
  type: book

book:
  title: "Phy2Q Roadmap"
  author: "Albert Zhang"
  date: "8/9/2025"
  chapters:
    - index.qmd

    - part: "Numerical Optimization"
      chapters:
        - numerical-optimization/introduction.qmd
        - numerical-optimization/unconstrained.qmd
        - numerical-optimization/lineSearch.qmd
        - numerical-optimization/gradDescent.qmd
        - numerical-optimization/newTon.qmd
        - numerical-optimization/quasiNewton.qmd
        - numerical-optimization/conjGrad.qmd
        - numerical-optimization/constrained.qmd
        - numerical-optimization/quadProg.qmd
        - numerical-optimization/seqQuadprog.qmd
        - numerical-optimization/penalty.qmd
        - numerical-optimization/interior.qmd
    - part: Monte-Carlo Methods
      chapters: 
        - monte-carlo/monte-carlo.qmd
    - part: "Machine Learning and Data Science Basics"
      chapters: 
        - ml-ds/highDimData.qmd
        - ml-ds/randomProj.qmd
        - ml-ds/SVD.qmd
    - part: "Machine Learning in Finance"
    - part: "Practice Machine Learning with Kaggle"
    - part: "Statistical Inference"
    - part: "Regression Analysis"
      chapters: 
        - reg-anly/slrInference.qmd
    - part: "Bayesian Modeling"
    - part: "Stochastic Process and Stochastic Integral"
      chapters: 
        - sp/prob.qmd
        - sp/bm.qmd
        - sp/stocInt.qmd
    - part: "Financial Basics"
    - part: "Stochastic Process in Finance"
      chapters: 
        - sp-in-finance/plan.qmd
    - references.qmd
      

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

number-depth: 2

filters: 
  - pseudocode


