# Probability Review

* **Sample space $\Omega$:** the set of all possible outcome of an experiment.
* **Event:** subsets of the sample space $\Omega$.
* **Impossible event:** is $\emptyset$.
* **Certain event:** is $\Omega$.
* **Bertrand's Paradox:** probability of chord intersect with inner circle. An example of different.

**Remark:** Events are subsets of $\Omega$, but subsets of $\Omega$ may not be an Event. We can therefore select subsets of $\Omega$, which are events and form a collection $\mathcal{F}$ (ie, $\mathcal{F} \subseteq 2^\Omega$ set of all subset of $\Omega$) and should have following property:
* **(a)** if $A, B \in \mathcal{F}$ then $A \cup B \in \mathcal{F}$ and $A \cap B \in \mathcal{F}$.
* **(b)** if $A \in \mathcal{F}$ then $A^c \in \mathcal{F}$.
* **(c)** $\emptyset \in \mathcal{F}$.

$\mathcal{F} \subseteq 2^\Omega$ satisfied above is called a field.

**Remark:**
* **(a)** $\bigcup_{i=1}^n A_i \in \mathcal{F}$, $\bigcap_{i=1}^n A_i \in \mathcal{F}$. close under finite Union or intersect.
* **(b)** This properties can be shown via easy coin toss experiment.

**Infinite union and dice:**
Consider an experiment: A coin is repeatedly tossed until the first head show up, try to find number of toss before this happen.
$\Omega = \{ \omega_1, \omega_2, \dots \}$. $\omega_i = \text{first i-lane toss i are head}$.
Event $A := \text{the first head shows up after even number of tosses}$.
$A := \{ \omega_2, \omega_4, \omega_6, \dots \} = \bigcup_{i=1}^\infty \omega_{2i}$.
$A$ should also be in the event space $\mathcal{F}$.

**$\sigma$-algebra / $\sigma$-field:**
Set of Events under infinite Union. Collection of subset of sample space $\mathcal{F} \subseteq 2^\Omega$, called a $\sigma$-algebra / $\sigma$-field if it satisfies following:
1.  $\emptyset \in \mathcal{F}$.
2.  if $A \in \mathcal{F}, A^c \in \mathcal{F} (A^c := \Omega - A) \rightarrow \Omega \in \mathcal{F}$.
3.  if $A_1, A_2, \dots \in \mathcal{F}$, then $\bigcup A_i \in \mathcal{F}, \bigcap A_i \in \mathcal{F}$.



---

## Probability measure

Suppose we have sample space $\Omega$, and $\sigma$-algebra $\mathcal{F}$. A probability measure is a function $P: \mathcal{F} \rightarrow [0, 1]$ satisfies:
1.  $P(\emptyset) = 0, P(\Omega) = 1$.
2.  If $A_1, A_2, \dots \in \mathcal{F}$ and are disjoint $(A_i \cap A_j = \emptyset, \text{for } i \neq j)$ then $P(\bigcup_{i=1}^\infty A_i) = \sum_{i=1}^\infty P(A_i)$.

The $(\Omega, \mathcal{F}, P)$ is called a probability space.

**Lemma 1.4:**
* **(a)** $P(A^c) = 1 - P(A)$.
* **(b)** if $A \subseteq B, P(A) \leq P(B)$.
* **(c)** $P(A \cup B) = P(A) + P(B) - P(A \cap B)$.
* **(d)** $P(\bigcup_{i=1}^n A_i) = \sum P(A_i) - \sum_{i<j} P(A_i \cap A_j) + \dots (-1)^{n+1} P(A_1 \cap \dots \cap A_n)$.

---

## Generated $\sigma$-field for uncountable $\Omega$

Suppose a collection of subset $A_\alpha \subseteq \Omega$ where $\alpha \in T$ not necessarily countable. The smallest $\sigma$-field $\mathcal{F}$ s.t. $A_\alpha \in \mathcal{F}$ for $\forall \alpha \in T$ is denoted as $\mathcal{F}(\{A_\alpha\})$.
Then $A_\alpha$ is called generator, and $\mathcal{F}(\{A_\alpha\})$ is called $\sigma$-field generated by $A_\alpha$.
$\sigma(\{A_\alpha\})$ is a $\sigma$-field, $A_\alpha \in \sigma$. Smallest $\sigma$-field over $A_\alpha, \forall \alpha \in T$.

**Remark:** if $\mathcal{A}_\alpha$ is $\sigma$-field for each $\alpha \in T$, then $\bigcap_{\alpha \in T} \mathcal{A}_\alpha$ is a $\sigma$-field.

**Borel $\sigma$-field:**
A Borel $\sigma$-field on $\mathbb{R}$ is a $\sigma$-field generated by $(a, b)$.
$\mathcal{B} = \sigma(\{(a, b), a < b \in \mathbb{R}\}) \iff \mathcal{F}(\{O \subseteq \mathbb{R} \text{ is open}\}) \iff \mathcal{F}(\{(-\infty, b], b \in \mathbb{R}\})$.

---

## Random Variable (R.V.)

Observable of probability space. A R.V. is a function $X: \Omega \rightarrow \mathbb{R}$ s.t. for $\alpha \in \mathbb{R}$ the set $\{\omega : X(\omega) \leq \alpha\}$ is in $\mathcal{F}$ (such function is also called $\mathcal{F}$-measurable (or just measurable)).
Equivalently, the measurable means $X$ is measurable in $\mathcal{F}$ if for $B \in \mathcal{B}(\mathbb{R}), X^{-1}(B) \in \mathcal{F}$.

**Remark:** The R.V. create a mapping between outcomes and real numbers, in a way s.t. outcomes that captured by any Borel set (could be record as an event of random space) is forming an events in Event space $\mathcal{F}$.

**$\sigma$-field generated by random variable:**
Suppose $X$ is R.V. on $(\Omega, \mathcal{F})$. The $\sigma$-field generated by $X$, $\sigma(X)$ is the smallest $\sigma$-field $\mathcal{G} \subseteq \mathcal{F}$ s.t. $X$ is still measurable on $(\Omega, \mathcal{G})$.

**Remark:** $\{X^{-1}(B) \mid B \in \mathcal{B}(\mathbb{R})\}$ is such smallest $\sigma$-algebra. Every $B \in \mathcal{B}(\mathbb{R})$ is inside $\mathcal{F}$, the smallest set from $X$ is $\{X^{-1}(B) \mid B \in \mathcal{B}(\mathbb{R})\}$. This contains all the information relevant to $X$. $\sigma(X)$ is thus the least amount of information relevant to $X$.

**Simple function:**
$X := \sum_{n=1}^N c_n I_{A_n}$ is a R.V. for finite $N$ and $c_n \in \mathbb{R}$. Have $A_n \in \mathcal{F}$ for any $n$ and $I_{A_n} := \begin{cases} 1, \omega \in A_n \\ 0, \omega \notin A_n \end{cases}$.

**Prop:** for every R.V. $X$, there exist a sequence of sample functions $X_n$ s.t. $X_n(\omega) \rightarrow X(\omega)$ as $n \rightarrow \infty$ for $\forall \omega \in \Omega$.

**Two R.V. same (almost surely):**
Suppose $X$ and $Y$ are R.V. defined on $(\Omega, \mathcal{F}, P)$, we says $X$ and $Y$ are almost surely (a.s.) the same if $P(\{\omega : X(\omega) \neq Y(\omega)\}) = 0$.

---

## Expected Value

Integration w.r.t. measure.

**Lebesgue integral:**
1.  **Simple R.V. Def:** Suppose $X$ on $(\Omega, \mathcal{F})$ is simple value R.V.. $X = \sum_{i=1}^k c_i I_{A_i}$ then define $\int_\Omega X dP := \sum_{i=1}^k c_i P(A_i)$.
2.  If $X$ is non-negative R.V. $\int_\Omega X dP := \sup_{Y \leq X, Y \text{ simple}} \int_\Omega Y dP$.
3.  If $X$ is general R.V., then $\int_\Omega X dP = \int_\Omega X^+ dP - \int_\Omega X^- dP$, $X^+ = \max(X, 0)$, $X^- = \max(-X, 0)$.



---

## Conditional probability

Let $(\Omega, \mathcal{F}, P)$ be a prob space and $A, B \in \mathcal{F}$ and $P(B) > 0$. The conditional probability of $A$, given $B$ is $P(A|B) := \frac{P(A \cap B)}{P(B)}$.

**Independence:**
This means $P(A|B) = P(A) \Rightarrow P(A \cap B) = P(A)P(B)$.

**Conditional Expectation:**
$E(X|B) = \frac{1}{P(B)} \int_B X dP$.

$E(X|Y)$, the expected value of R.V. $X$, given another R.V. $Y$ known. Consider the case where $Y = \sum_{i=1}^m c_i I_{A_i}$, suppose $c_i$ are distinct.
$Y(\omega) = \begin{cases} c_1, \omega \in A_1 \\ \dots \\ c_m, \omega \in A_m \end{cases}$
$E(X|Y) = \begin{cases} \frac{1}{P(A_1)} \int_{A_1} X dP, A_1 \\ \dots \\ \frac{1}{P(A_m)} \int_{A_m} X dP, A_m \end{cases}$

**Def:** Let $X, Y$ be R.V. defined on $\Omega$, the conditional expectation $E(X|Y)$ is random variable $Z$ s.t.:
1.  $Z$ is $\sigma(Y)$ measurable.
2.  $\int_A X dP = \int_A Z dP$ for $\forall A \in \sigma(Y)$.

**Remark:** $E(X|\mathcal{V})$ can be understand as an estimate of R.V. $X$ constructed from the information in $\sigma$-field $\mathcal{V}$.