---
title: "Stochastic Integral"
date: "2026-03-17"
---

To define the **stochastic integral** (specifically the Itô integral), we begin with an intuitive definition for simple functions, in a manner analogous to the definition of the Riemann integral.

## Itô's Stochastic Integral for Step Processes
Let $0 = t_0 < t_1 < \dots < t_n = T$ be a partition of $[0, T]$.

:::{#def-stepProcess}
## Step Process
A step process $(G_t^n)_{t \in [0, T]}$ defined on a partition $0 = t_0 < t_1 < \dots < t_n = T$ is:
$$
G_t^n = \sum_{k=0}^n \xi_{k} I_{\{t_{k} \le t < t_{k+1}\}}
$$
where $\xi_k$ is $\mathcal{F}_{t_k}$-measurable, and indicator function $I_{\{t_{k} \le t < t_{k+1}\}}$ is:
$$
I_{\{t_{k-1} \le t < t_k\}} = 
\begin{cases} 
1 & t_{k} \le t < t_{k+1} \\ 
0 & \text{otherwise} 
\end{cases}
$$
:::

:::{#def-stochIntStep}
## Itô's Stochastic Integral for Step Processes
For a step process $(G^n_t)_{t\in[0, T]}$ on partition $0 = t_0 < t_1 < \dots < t_n = T$, we define the Itô's stochastic integral $I_t^n$ for $t\in[t_k, t_{k+1}]$ as:
$$
I_t^n := \int_0^t G_u^n \, dB_u = \sum_{i=0}^{k-1} \xi_i (B_{t_{i+1}} - B_{t_i}) + \xi_k (B_t - B_{t_k})
$$
where $B_t$ is a Brownian motion. We can also denote this as $\mathrm{d}I_t^n = G_u^n \mathrm{d}B_u$.
:::

:::{.callout-note}
An intuitive understanding of this deifinition is to think $t_0, \dots, t_n$ as trading days, $B(t_i)$ as the price on day $t_i$, and $\xi_i$ as the number of shares bought at $t_i$ and held until $t_{i+1}$. The total gain of the asset (which would stands for an "integral") would be $\sum_{\text{trading days}} \text{shares} \times \text{price change}$.
:::

### Properties of step process integrals

:::{#prp-martingaleStep}
## Martingale Property
\
$I_t^n$ is a continuous martingale, with $I_0^n = 0$.
:::

:::{#prf-martingaleStep}
Let $0 \le s < t$. To show $I_s^n = E(I_t^n | \mathcal{F}_s)$, or equivalently, $E(I_t^n - I_s^n | \mathcal{F}_s) = 0$:

Suppose $s \in [t_l, t_{l+1}]$ and $t \in [t_k, t_{k+1}]$. Then:
$$
\begin{align*}
I_t^n - I_s^n &= \xi_k (B_t - B_{t_k}) + \dots + \xi_l (B_{t_{l+1}} - B_{t_l}) - \xi_l (B_s - B_{t_l}) \\
&= \xi_k (B_t - B_{t_k}) + \dots + \xi_l (B_{t_{l+1}} - B_{t_s})
\end{align*}
$$
Taking conditional expectations:
$$
\begin{align*}
E[\xi_k(B_t - B_{t_k}) | \mathcal{F}_s]
&= E[E(\xi_k(B_t - B_{t_k}) | \mathcal{F}_{t_k}) | \mathcal{F}_s]
\\
&= E[\xi_k E(B_t - B_{t_k}| \mathcal{F}_{t_k}) | \mathcal{F}_s]
= 0
\end{align*}
$$
Here we have used the tower property, the fact that $\xi_k$ is $\mathcal{F}_{t_k}$-measurable and the property of Brownian motion. Similarly argument is applied for all other terms except the last one. For the last term, we have:
$$
E[\xi_l (B_{t_{l+1}} - B_s) | \mathcal{F}_s] = \xi_l E(B_{t_{l+1}} - B_s | \mathcal{F}_s) = 0
$$
since $\xi_l$ is $\mathcal{F}_{t_l}$-measurable thus also $\mathcal{F}_{t_s}$-measurable.
Therefore, $I_t^n$ is a continuous martingale.
:::

:::{#prp-itôIsometryStep}
## Itô Isometry
$$
E[(I_t^n)^2] = E\left[\int_0^t (G_u^n)^2 du\right]
$$
:::

:::{#prf-itôIsometryStep}
Let's denote $\Delta B_i = B_{t_{i+1}} - B_{t_i}, i < k$, and $\Delta B_k = B_t - B_{t_k}$. Then:
$$
\begin{align*}
E[(I_t^n)^2] 
&= E\left[\left( \sum_{i=0}^{k} \xi_i \Delta B_i + \xi_k \Delta B_k \right)^2\right] \\
&= E\left[\sum_i \xi_i^2 (\Delta B_i)^2 + 2 \sum_{i \ne j} \xi_i \xi_j \Delta B_i \Delta B_j\right]
\end{align*}
$$
For $i \ne j$ (say $i < j$), $\xi_i \xi_j \Delta B_i$ is independent of $\Delta B_j$ (they are all $F_{t_j}$ measurable), so $E[\xi_i \xi_j \Delta B_i \Delta B_j] =E[\xi_i \xi_j \Delta B_i]E[\Delta B_j] = 0$.
Thus,
$$
\begin{align*}
E[(I_t^n)^2] &= E\left[\sum_i \xi_i^2 (\Delta B_i)^2\right] = \sum_i E(\xi_i^2) E((\Delta B_i)^2) \\
&= \sum_i E(\xi_i^2)(t_{i+1} - t_i) = E\left[\int_0^t (G_u^n)^2 du \right]
\end{align*}
$$
:::

:::{#prp-quadVarStep}
## Quadratic Variation

We defined the quadratic variation of $I_t^n$ similarly as for Brownian motion:
$$
[I_t^n, I_t^n] = \sum_i (\xi_i (B_{t_{i+1}} - B_{t_i}))^2,
$$
and 
$$
\langle I^n_t, I^n_t \rangle = E\left[\sum_i (\xi_i(B_{t_{i+1}} - B_{t_i}))^2\middle|\mathcal{F}_{t_i}\right]
$$
then we have:
$$
\lim_{\|\Delta\| \to 0} [I^n, I^n] = \langle I^n, I^n \rangle = \int_0^t (G_u^n)^2 du
$$
:::
:::{.callout-note}
* $\|\Delta\| = \max_{i} |t_{i+1} - t_i|$
* The convergence here is in $L^2$ sense, which implies the convergence in probability.
* The last interval is $B_t - B_{t_k}$.
* We can denote this in differential form as $(\mathrm{d}I)^2=(G_t^n)^2(\mathrm(d)B_t)^2=(G^n_t)^2\mathrm{d}t$.
:::

:::{#prf-quadVarStep}
$$
\begin{align*}
\langle I^n_t, I^n_t \rangle &= E\left[\sum_i \xi_i^2 (B_{t_{i+1}} - B_{t_i})^2\middle|\mathcal{F}_{t_i}\right]\\
&= \sum_i \xi_i^2 E((B_{t_{i+1}} - B_{t_i})^2|\mathcal{F}_{t_i})\\
&= \sum_i \xi_i^2 (t_{i+1} - t_i)\\
&= \int_0^t (G_u^n)^2 du
\end{align*}
$$

The proof of convergence of quadratic variation is similar to the proof of convergence of Brownian motion quadratic variation.
:::

:::{#prp-martingaleStep2}
## Martingale Property 2
$$
(I_t^n)^2 - \int_0^t (G_u^n)^2 du
$$
is a martingale.
:::

:::{#prf-martingaleStep2}
Need to show for any $0 \le s < t$:
$$
E[M_t | \mathcal{F}_s] = M_s
$$
where $M_t = (I_t^n)^2 - \int_0^t (G_u^n)^2 du$.

That is,  to show $E[M_t - M_s | \mathcal{F}_s] = 0$. Compute:
$$
\begin{align*}
M_t - M_s 
&= \big((I_t^n)^2 - (I_s^n)^2\big) - \int_s^t (G_u^n)^2 du \\
(I_t^n)^2 - (I_s^n)^2 
&= \big(I_t^n - I_s^n\big)^2 + 2 I_s^n (I_t^n - I_s^n)
\end{align*}
$$
So,
$$
E[M_t - M_s | \mathcal{F}_s]
= E\left[ (I_t^n - I_s^n)^2 | \mathcal{F}_s \right]
+ 2 I_s^n E[I_t^n - I_s^n | \mathcal{F}_s]
- E\left[\int_s^t (G_u^n)^2 du | \mathcal{F}_s\right]
$$
Since $I_t^n$ is a martingale, $E[I_t^n - I_s^n | \mathcal{F}_s] = 0$. Using the similar argument in @prf-itôIsometryStep, we have:
$$
\begin{align*}
E\left[(I_t^n - I_s^n)^2 | \mathcal{F}_s\right] &= \sum_i E[\xi_i^2\Delta B_i^2|\mathcal{F}_s] = \sum_i E[\xi_i^2|\mathcal{F}_s](t_{i+1} - t_i) \\
&= E\left[\int_s^t (G_u^n)^2 du | \mathcal{F}_s\right]
\end{align*}
$$
Thus, $E[M_t - M_s | \mathcal{F}_s] = 0$. Therefore, $(I_t^n)^2 - \int_0^t (G_u^n)^2 du$ is a martingale.
:::

## Stochastic Integral for General Processes

To define 
$$
\int_0^T C_u dB_u
$$
for general $C_t$, approximate $C_t$ by step processes.

Let $T$ be fixed.

**Define:**
$$
L^2(0, T) = \left\{ (C_t)_{0 \le t \le T} : C_t \text{ is measurable w.r.t. } \mathcal{F}_t
,\quad
E\left[\int_0^T C_t^2 dt \right] < \infty \right\}
$$

There exists a sequence of bounded step processes $(C^n)_t \in L^2(0, T)$ such that
$$
E\left[\int_0^T |C_u - C_u^n|^2 du \right] \to 0
$$

**Definition:**
$$
Z_t = \int_0^t C_u dB_u := \lim_{n \to \infty} \int_0^t C_u^n dB_u
$$
where $(C^n)_t$ is a sequence of step processes as above. This is equivalent to $dZ_t = C_t dB_t$.

---

### Properties

- $Z_t$ is a continuous martingale.
- **Itô Isometry:** $E(Z_t^2) = E\left[\int_0^t C_u^2 du\right]$.
- **Quadratic Variation:** $\langle Z, Z \rangle_t = \int_0^t C_u^2 du$.
- $Z_t^2 - \int_0^t C_u^2 du$ is a martingale.
- $\int_0^t (dZ_u)^2 = \int_0^t C_u^2 du$. Justification:
  $$
  (dZ_t)^2 = C_t^2 dt = d\langle Z, Z \rangle_t
  $$

Observation:
$$
E[(Z_t - Z_s)^2 | \mathcal{F}_s] = E[Z_t^2 - Z_s^2 | \mathcal{F}_s]
$$
Letting $s = t_{k-1}$ and $t = t_k$:
$$
E[Z_{t_k}^2 - Z_{t_{k-1}}^2 | \mathcal{F}_{t_{k-1}}] = E[\langle Z, Z \rangle_{t_k} - \langle Z, Z \rangle_{t_{k-1}} | \mathcal{F}_{t_{k-1}}]
$$