# Line Search Methods
The line search methods choose a direction $\mathbf{p}_k$ and search along this direction for next point hoping the function value decree, and continue this process until converge. In general, we hope to find the step length s.t. 
$$
\min_{\alpha>0}f(\mathbf{x}_k+\alpha\mathbf{p}_k)
$$

::: {#rem-lineSearch1}
* Through the minimization problem can be solved exactly, but this is typically not desired as it is expensive to find the exact solution. (methods attained $\arg\min_{\alpha>0}$ are called *exact line search*)
* Practically, the step length is approximately solved through limit number of trail steps tile meeting certain conditions, referred as *inexact line search*. 
:::

For line search methods, the algorithm generally has two major steps:

1. Pick descent direction

2. Choose appropriate step length $\alpha$ to update

We first discuss generally a descent direction, then in details about step length selection.

::: {.callout-tip}
## What is a descent direction
In general, we want the update $x_{k+1}=x_k+\alpha_k\mathbf{p}_k$ to always decrease the function value, for small enough step length $\alpha_k$.
:::

::: {#def-descentDir}
## Descent Direction
$\mathbf{p}\in\mathbb{R}^n$ is called a descent direction for $f:\mathbb{R}^n\rightarrow\mathbb{R}$ at point $\mathbf{x}\in\mathbb{R}^n$ if 
$$
f(\mathbf{x} + \alpha p )<f(x),\quad\text{for sufficient small } \alpha>0
$$
:::

::: {#rem-descentDir}
* The @def-descentDir is equivalent as stating $\mathbf{p}^T\nabla f(x)<0$, which is often used to select descent direction in practice. This can be seen from the Taylor expansion of $f(\mathbf{x+\alpha \mathbf{p}})$
:::

Once the descent direction has been selected, we still need to pick up a appropriate step length $\alpha$. 

In the inexact line search methods, we need certain condition that stop the iteration of finidng $\alpha$. The simplest choice would be just require a decrease in function value, i.e. $f(\mathbf{x}_k + \alpha_k\mathbf{p_k})< f(\mathbf{x_k})$. However, this condition is not sufficient to ensure the convergence to a local minimizer. 

:::{#exm-tooSmall}
example of too large step length here

:::

The @exm-tooSmall shows that the too small function value drop should be avoid otherwise the algotihem would not be efficient. 

## Sufficient Decrease Condition
To avoid this issue, a *sufficient decrease condition* can be imposed. As the name suggested, the condition imposed the the drop of function value for a specific chosed step length should be suffificently large.

One popular measure of sufficient decrease is the *Armijo condition*, which state as follow

:::{#def-armijo}
## Armijo Condition
For $\mathbf{x}_k\in\mathbb{R}^n$ and descent direction $\mathbf{p}_k\in\mathbb{R}^n$, step length $\alpha_k$ satisfied Armijo condition if
$$
f(\mathbf{x}_k+\alpha_k\mathbf{p}_k)\leq f(\mathbf{x}_k) + c_1\alpha_k\nabla^Tf(\mathbf{x}_k)\mathbf{p}_k,\quad \text{for some } c_1\in (0, 1)
$$
:::

:::{.callout-tip}
## Idea behind
We can denote the LHS of the inequality in @def-armijo as a function of $\alpha$ as $\phi(\alpha)$, and the RHS as a linear function $l(\alpha)$ with a negative slop $c_1\nabla^Tf(\mathbf{x}_k)\mathbf{p}_k$. Note that this slop is between the horizontal line and the tangent line at $\phi(0)$. The *Armijo condition* is thus requiring the selected step length drop the function value larger than a predifined linear function, which derease slower than the steepest local function drop. 
:::

Figure shows the acceptable region of the *Armijo line search*

In practice, the *Armijo condition* can be satisified using *Backtracing line search* algorithm 

### Backtracking Algorithm
The idea of the backtracking line search is to start with a relatively large step length and shrink $\alpha$ every iteration till the *Armijo condition* is satisfied.

```python
import numpy as np
from numpy.typing import NDArray
from typing import Callable

def backtracking_search(
    f: Callable,
    gradf_xk: NDArray,
    xk: NDArray,
    pk: NDArray,
    alpha0: float,
    c1: float = 1e-4,
    tau: float = 0.5,
) -> float:
    """Step length search using Armijo backtracking methods

    Args:
        f (Callable): objective function
        gradf (Callable): gradient of objective function
        xk (NDArray): current position
        pk (NDArray): descent direction
        alpha0 (float): initial step length. Default to 1. 
        c1 (float): control variable for Armijo condition. Default to 1e-5
        tau (float): contraction coefficient for step length. Default to 0,5. 

    Returns:
        float: final step length
    """
    alpha = alpha0
    f_xk = f(xk)
    while f(xk + alpha * pk) > f_xk + c1 * alpha * np.dot(gradf_xk, pk):
        alpha = tau * alpha
    return alpha
```

:::{.callout-note}
* The initial guess of step length typically is 1, but might vary depens on $\mathbf{p}_k$
* Require only function evaluation during the search
* Will terminated in finite steps
* The backtracking approach avoid too small step length as it star with large step and will usually stop before the step length becomes too small.
:::

Though the *Armijo condition* ensure the sufficient decrease of the function value. However, the selected step length could be too small and leading to inefficient progress. The following *curvature condition* make sure the the step length would not be too short.

## Curvature Condition

:::{#def-curvature}
## Curvature Condition
For $\mathbf{x}_k\in\mathbb{R}^n$ and descent direction $\mathbf{p}_k\in\mathbb{R}^n$, step length $\alpha_k$ satisfied curvature condition if
$$
\nabla^Tf(\mathbf{x}_k+\alpha_k\mathbf{p}_k)\mathbf{p_k}\geq c_2\nabla f(\mathbb{x}_k),\quad c_2\in(c_1, 1)
$$ 
$c_1$ is the constant from @def-armijo
:::

:::{.callout-tip}
## Idea behind
Again if we consider $\phi(\alpha) = f(\mathbf{x} + \alpha\mathbf{p})$ as a function if $\alpha$. Then the LHS of the inequality in @def-curvature is $\phi^\prime(\alpha_k)$, which is the slope of the tangent line at the accepted step length. Since the RHS is negative, the curvature condition requires the curvature of $\phi$ at the accepted step length should be "flat" comparing to that at the starting point, which is measured by the coefficient $c_2$. Thus, the accepted step length can not be too close to the staring point
:::

**Figure** show the accpetable region satified curvature condition


Combine the two condition together, we get the *Wolf conditions*

## Wolf Condition
:::{#def-wolf}
## Wolf Condition
For $\mathbf{x}_k\in\mathbb{R}^n$ and descent direction $\mathbf{p}_k\in\mathbb{R}$, step length $\alpha_k$ satisfied Wolf condition if
$$
\begin{aligned}
f(\mathbf{x}_k+\alpha_k\mathbf{p}_k)&\leq f(\mathbf{x}_k) + c_1\alpha_k\nabla^Tf(\mathbf{x}_k)\mathbf{p}_k\\
\nabla^Tf(\mathbf{x}_k+\alpha_k\mathbf{p}_k)\mathbf{p_k}&\geq c_2\nabla f(\mathbb{x}_k)
\end{aligned}
$$
for some $0<c_1<c_2<1$
:::

:::{.callout-note}
* If $c_1\geq c_2$, the exsistance of Wolf condition might not be satisfied
* The Wolf condition requires evaluations of both function and gradient values at each iteration
:::

### Line Search Algorithm Satisfying Wolf Condition
```python
def wolf_search(
        f: Callable[[NDArray], float],
        gradf: Callable[[NDArray], NDArray],
        xk: NDArray,
        pk: NDArray,
        c1: float=1e-4,
        c2: float=0.9,
        max_iter: int=1000
) -> float:
    """wolf line search methods

    Args:
        f (Callable[[NDArray], float]): objective function
        gradf (Callable[[NDArray], float]): gradient of objective function
        xk (NDArray): current position for starting the line search
        pk (NDArray): current search direction
        c1 (float, optional): parameter for Amijor contion. Defaults to 1e-4.
        c2 (float, optional): parameter for curvature condition. Defaults to 0.9.
        max_iter(float, optional): maximum iteration of line search. Defaults to 1000.
    Returns:
        float: return the step length
    """    
    
    alpha = 1
    alpha_l = 0
    alpha_u = np.inf

    f_xk = f(xk)
    gradf_xk = gradf(xk)
    phi_prime_0 = np.dot(gradf_xk, pk)

    # check c1 < c2:
    if c1 > c2:
        raise ValueError("c1 must smaller than c2")
    
    # if the input search direction is not descent direction, just return
    if phi_prime_0 >= 0:
        return 1

    counter = 0
    while True:
        # break the line search if the iteration take to much
        if counter > max_iter:
            return alpha
        # if armijo condition not satisfied, shrink the upper bond of allowed step length
        if f(xk + alpha * pk) > f_xk + c1 * alpha * phi_prime_0:
            alpha_u = alpha

        else:

            # if armojo satsified but curvature condition is not, increase the lower bond of allowed step length
            if np.dot(gradf(xk + alpha * pk), pk) < c2 * phi_prime_0:
                alpha_l = alpha
            else:
                return alpha
        
        # if the Armijo condition has not been violated once, increase the lower bound
        if alpha_u < np.inf:
            alpha = (alpha_l + alpha_u) / 2
        else:
            alpha = 2 * alpha
        counter += 1
```